/*
 * main.cpp
 * DO NOT EDIT THIS FILE
 */

#include <memory>
#include <stdlib.h>
#include <time.h>

#include "world.hpp"
#include "entity.hpp"
#include "human.hpp"
#include "zombie.hpp"
#include "runner.hpp"
#include "clicker.hpp"
#include "stalker.hpp"
#include "bloater.hpp"

#define WORLD_WIDTH 100 // Based on the problem statement
#define WORLD_HEIGHT 100
#define NUM_HUMANS 100
#define NUM_RUNNERS 10
#define NUM_STALKERS 8
#define NUM_CLICKERS 4
#define NUM_BLOATERS 2

using namespace std;

int main()
{
  // srand(time(NULL));
  World world(WORLD_WIDTH, WORLD_HEIGHT);
  world.populate(NUM_HUMANS, NUM_RUNNERS, NUM_STALKERS, NUM_CLICKERS, NUM_BLOATERS);
  world.print();
  // world.runSimulation();
  // unique_ptr<Entity> tes;

  // tes = unique_ptr<Entity>(new Human(1,2));
  // tes->print();
  

  return 0;
}